---
title: "knitr dark mode - flextable"
brand:
  light: ../united-brand.yml
  dark: ../slate-brand.yml
execute:
  echo: false
  warning: false
---

```{r}
#| echo: false
#| warning: false
library(flextable)

flextable_theme_colors = function(x, bg, fg) {
  if (!inherits(x, "flextable")) {
    stop("flextable_theme_colors only supports flextable objects.")
  }
  x <- bg(x, bg = bg, part = "all")
  x <- color(x, color = fg, part = "all")
  autofit(x)
}

flextable_theme_brand <- function(brand_yml) {
  brand <- yaml::yaml.load_file(brand_yml)
  bg <- brand$color$background
  fg <- brand$color$foreground
  (function(x, ...) flextable_theme_colors(x, bg, fg))
}
```

```{r}
#| echo: false
#| warning: false
united_theme <- flextable_theme_brand('../united-brand.yml')
slate_theme <- flextable_theme_brand('../slate-brand.yml')
```

```{r}
#| renderings: [light, dark]

ft <- flextable(airquality[ sample.int(10),])
ft <- add_header_row(ft,
  colwidths = c(4, 2),
  values = c("Air quality", "Time")
)
ft <- theme_vanilla(ft)
ft <- add_footer_lines(ft, "Daily air quality measurements in New York, May to September 1973.")
ft <- color(ft, part = "footer", color = "#666666")
ft <- set_caption(ft, caption = "New York Air Quality Measurements")

ft |> united_theme()
ft |> slate_theme()
```

Here's a [link](https://example.com).

{{< lipsum 2 >}}
