---
title: "dark mode - ggiraph"
brand:
  light: ../united-brand.yml
  dark: ../slate-brand.yml
---

```{r}
#| echo: false
#| warning: false
library(knitr)

ggplot_theme <- function(bgcolor, fgcolor) {
  library(ggplot2)
  library(ggiraph)
  theme_minimal(base_size = 11) %+%
    theme(
      panel.border = element_blank(),
      panel.grid.major.y = element_blank(),
      panel.grid.minor.y = element_blank(),
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank(),
      text = element_text(colour = fgcolor),
      axis.text = element_text(colour = fgcolor),
      rect = element_rect(colour = bgcolor, fill = bgcolor),
      plot.background = element_rect(fill = bgcolor, colour = NA),
      axis.line = element_line(colour = fgcolor),
      axis.ticks = element_line(colour = fgcolor)
    )
}

brand_ggplot <- function(brand_yml) {
  brand <- yaml::yaml.load_file(brand_yml)
  ggplot_theme(brand$color$background, brand$color$foreground)
}
```

```{r}
#| echo: false
#| warning: false
united_theme <- brand_ggplot("../united-brand.yml")
slate_theme <- brand_ggplot("../slate-brand.yml")
```

```{r}
#| renderings: [light, dark]
cars <- ggplot(mtcars, aes(mpg, wt)) +
  geom_point_interactive(aes(colour = factor(cyl), tooltip = rownames(mtcars))) +
  scale_colour_manual(values = c("darkorange", "purple", "cyan4"))

girafe(ggobj = cars + united_theme)
girafe(ggobj = cars + slate_theme)
```
