---
title: "knitr dark mode - thematic"
format:
  html:
    css: ../light-dark.css
    theme:
      light: united
      dark: slate
    keep-md: true
execute:
  echo: false
  warning: false
filters:
  - light-dark-knitr.lua
---

```{r}
#| echo: false
#| warning: false
library(ggplot2)
library(svglite)

thematic_brand <- function(brand_yml) {
  brand <- yaml::yaml.load_file(brand_yml)
  (function()
        thematic::thematic_rmd(
        bg=brand$color$background,
        fg=brand$color$foreground,
    ))
}
united_brand <- thematic_brand('../united-brand.yml')
slate_brand <- thematic_brand('../slate-brand.yml')

# only works with ggplot (ggsave uses ggplot's get_last_plot)
# normally calling the device will initialize it and
# then knitr's plot2dev (the caller of this device) will print the plot to the device
# instead, this writes the plot via ggsave which also initializes a device and then prints the plot
# darksvglite <- function(file, width, height, ...) {
#     slate_brand()
#     ggsave(filename = file,
#         width = width,
#         height = height,
#         device = "svg",
#         bg = "transparent"
#     )
# }

# .dark.svg is produced but there is almost no difference between light and dark
# (slate color is applied to one rect in patchwork light.svg, not visible)
darksvglite <- function(file, width, height, ...) {
    slate_brand()
    svglite(file, width, height)
}

# trying various incantations to no effect
# darksvglite <- function(file, width, height, ...) {
#     last.dev <- dev.cur()
#     on.exit({ dev.off(); dev.set(last.dev) })
#     p <- recordPlot()
#     slate_brand()
#     svglite(file, width, height)
#     replayPlot(p)
# }
```

## ggplot

```{r}
#| dev: [svglite,darksvglite]
#| fig.ext: [.light.svg, .dark.svg]
united_brand()
ggplot(palmerpenguins::penguins, aes(x=bill_length_mm, y=bill_depth_mm)) + geom_point()
```

## base R graphics

```{r}
#| dev: [svglite,darksvglite]
#| fig.ext: [.light.svg, .dark.svg]
united_brand()
plot(
    palmerpenguins::penguins$body_mass_g,
    palmerpenguins::penguins$bill_length_mm,
)
```

## patchwork


```{r}
#| dev: [svglite,darksvglite]
#| fig.ext: [.light.svg, .dark.svg]
library(ggplot2)
library(patchwork)

#generate three scatterplots
plot1 <- ggplot(mtcars, aes(mpg, wt)) +
  geom_point()

plot2 <- ggplot(mtcars, aes(mpg, disp)) +
  geom_point()

plot3 <- ggplot(mtcars, aes(mpg, hp)) +
  geom_point()

#display all three scatterplots in same graphic
united_brand()
plot1 + plot2 + plot3
```


Here's a [link](https://example.com).

{{< lipsum 3 >}}
