---
title: "knitr dark mode - flextable"
format:
  html:
    css: ../light-dark.css
    theme:
      light: united
      dark: slate
    keep-md: true
execute:
  echo: false
  warning: false
filters:
  - at: pre-ast
    path: light-dark-cod-sequence.lua
---

```{r}
#| echo: false
#| warning: false
library(flextable)

flextable_brand_theme <- function(brand_yml) {
  brand <- yaml::yaml.load_file(brand_yml)

  (function(x, ...) {
    if (!inherits(x, "flextable")) {
      stop("Functions generated by flextable_brand_theme only support flextable objects.")
    }
    x <- bg(x, bg = brand$color$background, part = "all")
    x <- color(x, color = brand$color$foreground, part = "all")
    autofit(x)
  })
}
united_theme <- flextable_brand_theme('../united-brand.yml')
slate_theme <- flextable_brand_theme('../slate-brand.yml')
```

```{r}
#| classes: quarto-light-dark-container
#| fig-cap: table caption

ft <- flextable(airquality[ sample.int(10),])
ft <- add_header_row(ft,
  colwidths = c(4, 2),
  values = c("Air quality", "Time")
)
ft <- theme_vanilla(ft)
ft <- add_footer_lines(ft, "Daily air quality measurements in New York, May to September 1973.")
ft <- color(ft, part = "footer", color = "#666666")
ft <- set_caption(ft, caption = "New York Air Quality Measurements")

ft <- united_theme(ft)
ft
ft <- slate_theme(ft)
ft

```

Here's a [link](https://example.com).

{{< lipsum 2 >}}
