---
title: "knitr dark mode - plotly for R"
format:
  html:
    css: ../light-dark.css
    theme:
      light: united
      dark: slate
    keep-md: true
execute:
  echo: false
  warning: false
filters:
  - light-dark-cod-sequence.lua
---

```{r}
#| echo: false
#| warning: false
library(plotly)

plotly_brand <- function(brand_yml) {
  brand <- yaml::yaml.load_file(brand_yml)
  return (function(plot)
    plot |> layout(paper_bgcolor = brand$color$background,
      plot_bgcolor = brand$color$background,
      font = list(color = brand$color$foreground)
  ))
}
united_theme <- plotly_brand('../united-brand.yml')
slate_theme <- plotly_brand('../slate-brand.yml')
```

### no caption or crossref

```{r}
#| renderings: [light, dark]
fig <- plot_ly(iris, x = ~Species, y = ~Sepal.Width, type = 'violin',
               box = list(visible = TRUE),
               meanline = list(visible = TRUE),
               points = 'all')

fig |> united_theme()

fig |> slate_theme()


# Load the iris dataset
data("iris")
```


### crossref, no caption

::: {#fig-plotly-sepal-length}

```{r}
#| renderings: [light, dark]

fig <- plot_ly(iris, x = ~Species, y = ~Sepal.Length, type = 'violin',
               box = list(visible = TRUE),
               meanline = list(visible = TRUE),
               points = 'all')

fig |> united_theme()

fig |> slate_theme()
```

:::

### caption, no crossref

::: {}
```{r}
#| renderings: [light, dark]

# Load the iris dataset
data("iris")

fig <- plot_ly(iris, x = ~Species, y = ~Petal.Width, type = 'violin',
               box = list(visible = TRUE),
               meanline = list(visible = TRUE),
               points = 'all')

fig |> united_theme()

fig |> slate_theme()
```

Violin plot of Petal Width by Species

:::


### caption and crossref

::: {#fig-plotly-petal-length}
```{r}
#| renderings: [light, dark]

# Load the iris dataset
data("iris")

fig <- plot_ly(iris, x = ~Species, y = ~Petal.Length, type = 'violin',
               box = list(visible = TRUE),
               meanline = list(visible = TRUE),
               points = 'all')

fig |> united_theme()

fig |> slate_theme()
```

Violin plot of Petal Length by Species

:::