---
title: "knitr dark mode - plotly in R"
format:
  html:
    css: light-dark.css
    theme:
      light: united
      dark: slate
    keep-md: true
execute:
  echo: false
  warning: false
filters:
  - light-dark-jupyter.lua
---

```{r}
#| echo: false
#| warning: false
library(plotly)

plotly_brand <- function(brand_yml) {
  brand <- yaml::yaml.load_file(brand_yml)
  return (function(plot)
    plot |> layout(paper_bgcolor = brand$color$background,
      plot_bgcolor = brand$color$background,
      font = list(color = brand$color$foreground)
  ))
}
united_theme <- plotly_brand('united-brand.yml')
slate_theme <- plotly_brand('slate-brand.yml')

start_cell <- function()
  cat(paste0('::: {.cell}\n'))

start_plot <- function(marker) {
  cat(paste0('::: {.cell-output-display .', marker, '}\n'))
}
end_cell <- end_plot <- function()
  cat('\n:::\n')
```

```{r}
#| output: asis

# Load the iris dataset
data("iris")

fig <- plot_ly(iris, x = ~Species, y = ~Sepal.Length, type = 'violin',
               box = list(visible = TRUE),
               meanline = list(visible = TRUE),
               points = 'all')

fig <- fig %>% layout(title = "Violin plot of Sepal Length by Species")

start_cell()
start_plot('quarto-light-marker')
fig |> united_theme()
end_plot()
start_plot('quarto-dark-marker')
fig |> slate_theme()
end_plot()
end_cell()

```

Here's a [link](https://example.com).

{{< lipsum 3 >}}
