---
title: "knitr dark mode - flextable"
brand:
  light: ../united-brand.yml
  dark: ../slate-brand.yml
execute:
  echo: false
  warning: false
---

```{r}
#| echo: false
#| warning: false
library(flextable)
library(knitr)

flextable_brand_theme <- function(brand_yml) {
  brand <- yaml::yaml.load_file(brand_yml)

  (function(x, ...) {
    if (!inherits(x, "flextable")) {
      stop("Functions generated by flextable_brand_theme only support flextable objects.")
    }
    x <- bg(x, bg = brand$color$background, part = "all")
    x <- color(x, color = brand$color$foreground, part = "all")
    autofit(x)
  })
}
united_theme <- flextable_brand_theme('../united-brand.yml')
slate_theme <- flextable_brand_theme('../slate-brand.yml')

# gives me text output, also light should be themes[theme] but it said that wasn't function
flextable_light_dark_init <- function(light, dark, default = light) {
  themes <- list(light = light, dark = dark)
  knit_print.flextable <- function(x, options, ...) {
    if (is.null(options$renderings)) {
      flextable:::print.flextable(default(x), ...)
    } else {
      for (theme in options$renderings) {
        flextable:::print.flextable(themes[theme](x), ...)
      }
    }
  }
  registerS3method("knit_print", "flextable", knit_print.flextable)
}

flextable_light_dark_init(united_theme, slate_theme)


```

```{r}
#| renderings: [light, dark]

ft <- flextable(airquality[ sample.int(10),])
ft <- add_header_row(ft,
  colwidths = c(4, 2),
  values = c("Air quality", "Time")
)
ft <- theme_vanilla(ft)
ft <- add_footer_lines(ft, "Daily air quality measurements in New York, May to September 1973.")
ft <- color(ft, part = "footer", color = "#666666")
ft <- set_caption(ft, caption = "New York Air Quality Measurements")

ft

```

Here's a [link](https://example.com).

{{< lipsum 2 >}}
