---
title: "knitr dark mode - thematic"
brand:
  light: ../united-brand.yml
  dark: ../slate-brand.yml
execute:
  echo: false
  warning: false
---

```{r}
#| echo: false
#| warning: false
library(ggplot2)

thematic_brand <- function(brand_yml) {
  brand <- yaml::yaml.load_file(brand_yml)
  thematic::thematic_rmd(
      bg=brand$color$background,
      fg=brand$color$foreground,
  )
}
```


### no crossref, no caption

```{r}
#| renderings: [light, dark]
thematic_brand('../united-brand.yml')
ggplot(palmerpenguins::penguins, aes(x=bill_length_mm, y=bill_depth_mm)) + geom_point()

thematic_brand('../slate-brand.yml')
ggplot(palmerpenguins::penguins, aes(x=bill_length_mm, y=bill_depth_mm)) + geom_point()
```

## ggplot
### with crossref but no caption

::: {#fig-thematic-ggplot}
```{r}
#| renderings:
#|   - dark
#|   - light
thematic_brand('../slate-brand.yml')
ggplot(palmerpenguins::penguins, aes(x=bill_length_mm, y=bill_depth_mm)) + geom_point()

thematic_brand('../united-brand.yml')
ggplot(palmerpenguins::penguins, aes(x=bill_length_mm, y=bill_depth_mm)) + geom_point()
```
:::

## base R graphics
### with caption but no crossref

::: {}
```{r}
#| renderings: [light, dark]
thematic_brand('../united-brand.yml')
plot(
    palmerpenguins::penguins$bill_length_mm,
    palmerpenguins::penguins$bill_depth_mm,
)

thematic_brand('../slate-brand.yml')
plot(
    palmerpenguins::penguins$bill_length_mm,
    palmerpenguins::penguins$bill_depth_mm,
)
```

thematic - base r graphics

:::

## patchwork
### with crossref and caption

::: {#fig-thematic-patchwork}
```{r}
#| renderings: [light, dark]
library(ggplot2)
library(patchwork)

#generate three scatterplots
plot1 <- ggplot(mtcars, aes(mpg, wt)) +
  geom_point()

plot2 <- ggplot(mtcars, aes(mpg, disp)) +
  geom_point()

plot3 <- ggplot(mtcars, aes(mpg, hp)) +
  geom_point()

#display all three scatterplots in same graphic
thematic_brand('../united-brand.yml')
plot1 + plot2 + plot3

thematic_brand('../slate-brand.yml')
plot1 + plot2 + plot3

```
thematic - patchwork
:::


Here's a [link](https://example.com).

{{< lipsum 3 >}}
