---
title: "knitr dark mode - plotly for R"
format:
  html:
    css: ../light-dark.css
    theme:
      light: united
      dark: slate
    keep-md: true
execute:
  echo: false
  warning: false
filters:
  - at: pre-ast
    path: light-dark-cod-sequence.lua
---

```{r}
#| echo: false
#| warning: false
library(plotly)

plotly_brand <- function(brand_yml) {
  brand <- yaml::yaml.load_file(brand_yml)
  return (function(plot)
    plot |> layout(paper_bgcolor = brand$color$background,
      plot_bgcolor = brand$color$background,
      font = list(color = brand$color$foreground)
  ))
}
united_theme <- plotly_brand('../united-brand.yml')
slate_theme <- plotly_brand('../slate-brand.yml')
```

```{r}
#| classes: quarto-light-dark-container

# Load the iris dataset
data("iris")

fig <- plot_ly(iris, x = ~Species, y = ~Sepal.Length, type = 'violin',
               box = list(visible = TRUE),
               meanline = list(visible = TRUE),
               points = 'all')

fig <- fig %>% layout(title = "Violin plot of Sepal Length by Species")

fig |> united_theme()

fig |> slate_theme()
```

Here's a [link](https://example.com).

{{< lipsum 3 >}}
